apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "crudmysql"
        - name: MYSQL_USER
          value: "ali"
        - name: MYSQL_PASSWORD
          value: "root"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql

      - name: server
        image: alihdr116/single-crud-nodejs-mysql-server
        env:
        - name: DB_HOST
          value: "localhost"  # Use localhost since they are in the same pod
        - name: DB_USER
          value: "ali"
        - name: DB_PASSWORD
          value: "root"
        - name: DB_NAME
          value: "crudmysql"
        ports:
        - containerPort: 8001

      - name: client
        image: alihdr116/single-crud-nodejs-mysql-client
        ports:
        - containerPort: 3000

      volumes:
      - name: mysql-data
        emptyDir: {}  # Or use a persistent volume if needed
