apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: my-app
    component: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP  # Internal service for MySQL

---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: my-app
    component: server
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP  # Internal service for the Node.js server

---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: my-app
    component: client
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort  # Expose the client externally
